const trending = [
  {
    name: "Restaurant 1",
    availableSeats: 30,
    totalSeats: 60,
    isReserved: false,
    isFavorite: true,
    image: "restaurant.png",
  },
  {
    name: "Restaurant 2",
    availableSeats: 30,
    totalSeats: 60,
    isReserved: false,
    isFavorite: true,
    image: "restaurant.png",
  },
  {
    name: "Restaurant 3",
    availableSeats: 30,
    totalSeats: 60,
    isReserved: true,
    isFavorite: false,
    image: "restaurant.png",
  },
  {
    name: "Restaurant 4",
    availableSeats: 30,
    totalSeats: 60,
    isReserved: false,
    isFavorite: false,
    image: "restaurant.png",
  },
  {
    name: "Restaurant 5",
    availableSeats: 30,
    totalSeats: 60,
    isReserved: true,
    isFavorite: false,
    image: "restaurant.png",
  },
  {
    name: "Restaurant 6",
    availableSeats: 30,
    totalSeats: 60,
    isReserved: false,
    isFavorite: true,
    image: "restaurant.png",
  },
];
